# This file created by conda-build 0+unknown
# meta.yaml template originally from:
# c:\users\ray\conda\anaconda\packages\cmake, last modified Mon Nov 21 11:52:59 2016
# ------------------------------------------------

package:
    name: cmake
    version: 3.9.1
source:
    sha256: d768ee83d217f91bb597b3ca2ac663da7a8603c97e1f1a5184bc01e0ad2b12bb
    url: https://cmake.org/files/v3.9/cmake-3.9.1.tar.gz
build:
    features:
        - vc14
    number: '0'
requirements:
    build:
        - python
        - m2-curl
        - m2-unzip
        - jom
        - zlib 1.2.*
    run:
        - zlib 1.2.*
test:
    commands:
        - cmake --version
    requires:
        - python
about:
    dev_url: https://gitlab.kitware.com/cmake/cmake/
    doc_url: https://cmake.org/documentation/
    home: http://www.cmake.org/
    license: BSD 3-clause
    license_family: BSD
    summary: CMake is an extensible, open-source system that manages the build process
